### ISSUE TITLE
Add Claims for Admin, Read, ReadWrite, Write, etc

### ISSUE THREAD

**Issue by nathanclevenger** [drivly/oauth.do#10]
We need to figure out the source of truth of where this lives ... in the short term we could maybe whitelist all of the members of the drivly organization as admins?  Although ... I wouldn't want to add the latency for an API call ... so for now maybe it's in an env var?

**Comment by sam-lippert** [comment]
How about the Users KV?

**Comment by sam-lippert** [comment]
Persistent KV claims added in https://github.com/drivly/oauth.do/commit/3835feb7efe05f476e42186df3e1e42aa7cde2c1

@sam-lippert @nathanclevenger @bryant22 should now all have the admin:edit claim.
