### ISSUE TITLE
Add /signup & /logout routes

### ISSUE THREAD

**Issue by nathanclevenger** [drivly/oauth.do#4]
Where were the routes by worker automated?  We probably need to add /signup and /logout routes. (/signup should do the same thing as login, but many users have the idea that they need to signup if they don't already have an account, although with OAuth it's essentially synonymous)

**Comment by sam-lippert** [comment]
where should we keep scripts for adding routes? api.cf?

**Comment by sam-lippert** [comment]
Tracked in https://github.com/drivly/api.cf/issues/3
